<?php

return [
    "value" => [
        "Rotating Home Page Logo",
        "Sector Banner",
        "Hilighted Banner",
        "Leading Employer Banner ( Top employer )",
        "Specific Content for Social Media ( Post related with client's company )",
        "Testimonials ( Reviews of working in client's Company )",
        "Employer News Letter and Employee News Letter ( Benefits to both )",
        "Video Content Creation (info Graphic) ( Video posting in employer page )",
        "Employer Profile with Photo",
        "Employer Branding Video",
        "Best Match Applicants (Position Title/ Experienced length / Job Function / Industry / Location/ Education)",
        "Questionnaire Screening ",
        "Website Integration ( Job site pages appear on client's website )",
        "Advance Applicant Management ( Resorting the cv  )",
        "CV Unlocking ( Top empolyer review unlock )",
        "Recommended Profile",
        "Multi Users ( Family account operating system )_1",
        "Multi Users ( Family account operating system )_2",
        "Employer User Group by Admin Access ( Controlling usage )",
        "Profile Save/ Cloud Storage",
        "Unlock and Save Profile under (5 years working Experience) ( Senior level view )",
        "Unlock and Save Profile Above (5 years working Experience) ( Senior level view )",
        "Posting the job",
        "Pre Qualifyation Question",
        "upgrade to Featured Job (Hilighted Job) from Job Posting (Below Trending Jobs )_1",
        "upgrade to Featured Job (Hilighted Job) from Job Posting (Below Trending Jobs )_2",
        "upgrade to Featured Job (Hilighted Job) from Job Posting (Below Trending Jobs )_3",
        "upgrade to Trending Job from Job Posting ( Top Jobs on homepage )_1",
        "upgrade to Trending Job from Job Posting ( Top Jobs on homepage )_2",
        "upgrade to Trending Job from Job Posting ( Top Jobs on homepage )_3",
        "upgrade to Trending job from Featured Job_1",
        "upgrade to Trending job from Featured Job_2",
        "upgrade to Trending job from Featured Job_3",
        "Invite to apply (Suitable candidates)",
        "Job Alert to Candidates",
        "Anonymous Posting ",
    ]
];